### ISSUE TITLE
Load a web page?

### ISSUE THREAD

**Issue by endolith** [d3n7/GPT-4-With-Plugins#3]
Is it possible to load URLs directly and navigate around a website link by link instead of Googling?

```
Response: Traceback (most recent call last):
  File "plugins/google.py", line 8, in <module>
    for i in search(args.query, advanced=True, num_results=6):
  File "/home/user/.local/lib/python3.8/site-packages/googlesearch/__init__.py", line 54, in search
    resp = _req(escaped_term, num_results - start,
  File "/home/user/.local/lib/python3.8/site-packages/googlesearch/__init__.py", line 23, in _req
    resp.raise_for_status()
  File "/home/user/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dponies%26num%3D8%26hl%3Den%26start%3D0&hl=en&q=EgQixX8MGK6EkqIGIjCiTk20W6evjWiQytEoTE4RWvYhvIn_GKEBnxlgMuE5X5q9E0qlPL724_Dp2O2tdpUyAXI
```

```
Oh, it seems that Google has blocked us. Sometimes when we use the Google search function too frequently, Google assumes that we are bots and blocks our access to their search engine. If you still need search results, I can try using a different search engine or wait and try again later.
```

**Comment by d3n7** [comment]
Yes, this is very possible. Just make a python script such as the following: https://www.geeksforgeeks.org/how-to-scrape-all-the-text-from-body-tag-using-beautifulsoup-in-python/, put it in the plugins folder, and add it to the command table.

The only reason I didn't include it is to save tokens. I just added a duckduckgo plugin which should work for when google blocks your IP, also.
